### ISSUE TITLE
请问支持yolov5m.pt或者yolov5l.pt吗？

### ISSUE THREAD

**Issue by wangtianlong1994** [Syencil/tensorRT#10]
还是说只能对yolov5x.pt进行加速？

**Comment by Syencil** [comment]
他们本质上都是一个东西啊，必然都可以使用

**Comment by ZJU-lishuang** [comment]
这个yolov5使用tensorrt可以加速吗，不是速度和原版没什么变化吗

**Comment by Syencil** [comment]
TRT加速最多的点就是将conv和bn融到一起，u版yolo实际上也做了，所以速度差距不太大。但是走C++ trt你可以有更多的选择fp16，int8，服务部署的话更方便，可以走多线程，这些都是python所做不到的

> 这个yolov5使用tensorrt可以加速吗，不是速度和原版没什么变化吗

**Comment by pengyang1225** [comment]
onnx2trt 会报错
 Found (Unnamed Layer* 156) [Unary]_output as a shape tensor output from a layer that does not support it
有解决方案吗

**Comment by Syencil** [comment]
没碰到过

> onnx2trt 会报错
> Found (Unnamed Layer* 156) [Unary]_output as a shape tensor output from a layer that does not support it
> 有解决方案吗

**Comment by Crystalxd** [comment]
> onnx2trt 会报错
> Found (Unnamed Layer* 156) [Unary]_output as a shape tensor output from a layer that does not support it
> 有解决方案吗

pip安装一个onnx-simplifier, 然后对转出的pytorch转出的onnx模型进行处理
仅需三步:
```
pip install onnx-simplifier
python -m onnxsim yolov5s.onnx yolov5s_sim.onnx
./onnx2trt yolov5s_sim.onnx -o yolov5s_sim.trt
```
