### ISSUE TITLE
使用cmake编译后，使用make指令报错。

### ISSUE THREAD

**Issue by ZJU-lishuang** [Syencil/tensorRT#11]
[ 20%] Linking CXX executable bin/yolo5
/usr/bin/ld: 找不到 -lyolo5trt

这个报错找不到yolo5trt库是什么原因？
cmakelist.txt里面还有哪些要改

**Comment by Syencil** [comment]
这个得看你实际需要来改cmake 
cmake不长，建议先理解一遍

**Comment by ZJU-lishuang** [comment]
我注释掉了yolov3，yolov5和resnet的生成，make指令才通过，这三个网络和其它的有什么不一样导致编译失败？
[ 42%] Linking CXX executable bin/yolov3
/usr/bin/ld: 找不到 -lyolo3trt
都是类似的错误。

**Comment by ZJU-lishuang** [comment]
CMakeLists.txt不对，可能是我cmake版本高了吧，我要编两次，先生成*trt.so的库，再编译执行程序。

**Comment by ZJU-lishuang** [comment]
[TRT] CUDA initialization failure with error 2. 

运行编译好的执行程序报错，请问这是什么原因。

**Comment by ZJU-lishuang** [comment]
将onnx转trt时报错
[5] Assertion failed: ctx->tensors().count(inputName)

**Comment by Syencil** [comment]
试试用最新的onnx-trt

**Comment by ZJU-lishuang** [comment]
opset=11时，tensorrt7.0报这个错，在detect层。

最新的onnx-trt是tensorrt7.1的，但本地环境tensorrt是7.0，请问pytorch升级1.5支持opset=12后能行吗，你那里pytorch，tensorrt版本是多少才成功的

**Comment by Syencil** [comment]
哪个模型出现问题 我这边是torch1.4 trt7.0 opset11

**Comment by ZJU-lishuang** [comment]
yolov5

**Comment by ZJU-lishuang** [comment]
支持你fork的那一版的模型

**Comment by ZJU-lishuang** [comment]
opset11在转yolov5到trt时没报错吗
[5] Assertion failed: ctx->tensors().count(inputName)

**Comment by Syencil** [comment]
没有报错 这个问题你看看你的onnx graph 用onnxsimplfier简化一下

**Comment by ZJU-lishuang** [comment]
torch1.3不能用onnxsim优化，torch1.4可以。
从nvidia官网下载的tensorrt7.0转onnx会报错。
使用github上的onnx-tensorrt7.0能转为trt。

我用github上的onnx-tensorrt7.0中编译生成的库直接替换nvidia官网下载的tensorrt7.0的对应的四个库，运行报错
`
[08/05/2020-15:16:23] [E] [TRT] INVALID_ARGUMENT: Cannot find binding of given name: 692
段错误
`

**Comment by ZJU-lishuang** [comment]
请问你们的tensorrt7.0怎么配的？

**Comment by ZJU-lishuang** [comment]
替换后能跑了，但是报错是下面这段代码
`
inputParams.OutputTensorNames = std::vector<std::string>{"output", "692", "693"};
`
我改为
`
inputParams.OutputTensorNames = std::vector<std::string>{"output"};
`
跑通了
请问 `"692", "693"`是什么参数，有什么用？

**Comment by ZJU-lishuang** [comment]
使用官方的模型[yolov5l.pt](https://drive.google.com/file/d/10yxASJmZS0GtBYbiS_G8DtP7oYugr2GG/view?usp=sharing)，测试图片能得到正确的结果。
使用转好的onnx模型，在本工程中不能得到正确的结果。[yolov5l.sim.onnx](https://drive.google.com/file/d/1aR__QxcGDlYzc4AHTVjJrz7lymlkU1ul/view?usp=sharing)
![render](https://user-images.githubusercontent.com/26588466/89414155-86fe5780-d75c-11ea-88aa-8705314b9c82.jpg)
![coco_1](https://user-images.githubusercontent.com/26588466/89414177-91205600-d75c-11ea-9c03-6588955de4f7.jpg)

**Comment by Syencil** [comment]
那个是你的onnx的网络输出名 你用哪个就得改成对应的 
检查你在yolo里面有没有转成BHWAC的格式

**Comment by ZJU-lishuang** [comment]
格式转了BHWAC的格式，onnx的网络输出名指的是什么，能举例说明一下吗，新手还不是很熟

**Comment by ZJU-lishuang** [comment]
我在上面提供了模型，请问你们那里跑出来的结果是对的吗

**Comment by ZJU-lishuang** [comment]
添加了正确的网络输出名
输出结果没有之前的异常，但是结果差于python的版本。
![render](https://user-images.githubusercontent.com/26588466/89767216-08266780-db2c-11ea-89a8-97284f234743.jpg)
请问这是否正常。

**Comment by ZJU-lishuang** [comment]
只有第一次序列化模型时是正常的。
后面再此运行图片结果异常。
![render](https://user-images.githubusercontent.com/26588466/89771332-b59c7980-db32-11ea-94f5-69eeb03bab5d.jpg)
请问这是哪不对。

**Comment by Syencil** [comment]
图像预处理的方式和原来的有些差异 改一下padding方式以及预处理的func

**Comment by hyaihjq** [comment]
> CMakeLists.txt不对，可能是我cmake版本高了吧，我要编两次，先生成*trt.so的库，再编译执行程序。

大佬，我遇到了和你一样的问题，什么叫先生成so，再生成可执行文件？
