### ISSUE TITLE
Retinanet  pytorch 转 onnx

### ISSUE THREAD

**Issue by qinxianglinya** [Syencil/tensorRT#12]
你好，请问你将mmdetection中Retinanet的模型转换为onnx是使用mmdetection提供的工具转换的吗？

**Comment by Syencil** [comment]
是的 opset设一下

**Comment by qinxianglinya** [comment]
> 是的 opset设一下

好的，谢谢，这个和mmdetection版本有关吗？

**Comment by Syencil** [comment]
影响不大 毕竟逻辑都是差不多的 可能有些细节需要修改 
大多数ATen都能找到替代的python方法

**Comment by qinxianglinya** [comment]
> 影响不大 毕竟逻辑都是差不多的 可能有些细节需要修改
> 大多数ATen都能找到替代的python方法

博主，你好。我将pth转换为onnx后，在解析onnx的时候，出现错误。
Input filename:   D:/retinanet_mmdetection/data/onnx/retinanet.onnx
ONNX IR version:  0.0.4
Opset version:    11
Producer name:    pytorch
Producer version: 1.3
Domain:
Model version:    0
Doc string:
----------------------------------------------------------------
WARNING: ONNX model has a newer ir_version (0.0.4) than this parser was built against (0.0.3).
WARNING: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
Successfully casted down to INT32.
While parsing node number 177 [Gather]:
ERROR: onnx2trt_utils.hpp:347 In function convert_axis:
[8] Assertion failed: axis >= 0 && axis < nbDims
[08/05/2020-08:41:04] [E] Parsing File Failed
[08/05/2020-08:41:04] [E] Init Session Failed!
请问这是什么原因呢？

**Comment by Syencil** [comment]
gather 的 axis dim不能为-1 改成正数

**Comment by qinxianglinya** [comment]
> gather 的 axis dim不能为-1 改成正数

我用netron看了一下，gather的axis为0，类型为int64。而且不清楚While parsing node number 177这个节点在哪里，我看gather的input name不是177。

**Comment by Syencil** [comment]
看你onnx的graph177对应什么

**Comment by ElegantLin** [comment]
```
Thread Pool Created! Total num of threads is  4
----------------------------------------------------------------
Input filename:   /home/xiaohu/tensorRT/retinanet.onnx
ONNX IR version:  0.0.6
Opset version:    11
Producer name:    pytorch
Producer version: 1.5
Domain:
Model version:    0
Doc string:
----------------------------------------------------------------
[05/23/2021-15:16:16] [W] [TRT] onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[05/23/2021-15:16:16] [W] [TRT] onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
ERROR: builtin_op_importers.cpp:3345 In function importTopK:
[8] Assertion failed: inputs.at(1).is_weights()
[05/23/2021-15:16:16] [E] Parsing File Failed
[05/23/2021-15:16:16] [E] Init Session Failed!
Segmentation fault (core dumped)
```

你好，我retinanet make成功以后，执行bin文件报错。转换retinanet的方法是用mmdetection自带的权重和config，也设置了opset-version为11，但是还是报错，请问你知道是怎么回事吗？

谢谢！
