### ISSUE TITLE
fcos bug

### ISSUE THREAD

**Issue by chaos1992** [Syencil/tensorRT#13]
hi，fcos.cpp的45行，
float tmp = sigmoid(cls_f[pos*length+c]) * cen_f[pos];

是不是应该写成
float tmp = sigmoid(cls_f[pos+length*c]) * cen_f[pos];

**Comment by Syencil** [comment]
嗯嗯 应该是的 CHW格式 和 Retinanet的decode保持一致

**Comment by chaos1992** [comment]
@Syencil 
在执行./bin/fcos时遇到一个问题：
[08/07/2020-10:53:38] [E] Serializing Engine Failed
[08/07/2020-10:53:38] [E] Init Session Failed!

操作步骤：
1、在tensorRT根目录下mkidr build -> cd build -> cmake .. -> make
2、./bin/fcos

我发现在执行make以后，并没有产生fcosInt8.calibration文件和fcos.serialized文件，请问是什么原因呢？望解答

这是我的CMakeList.txt里的部分路径：
set(tensorrt_dir /home/***/programs/tensorRT/3rdParty/tensor-rt)
set(project_dir /home/***/programs/tensorRT)（这个是你的工程的目录）
include_directories(${tensorrt_dir}/include)
include_directories(${project_dir}/include)
link_directories(${tensorrt_dir}/lib)
link_directories(${project_dir}/source)
link_directories(${project_dir}/lib)（这个有点奇怪，你的工程的根目录下没有lib文件夹。。。）

这是fcos_main里的部分路径：
trtParams.CalibrationTablePath = "/home/***/programs/tensorRT/data/fcosInt8.calibration";
trtParams.CalibrationImageDir = "";
trtParams.OnnxPath = "/home/***/programs/tensorRT/onnx/fcos.onnx";
trtParams.SerializedPath = "/home/***/programs/tensorRT/data/onnx/fcos.serialized";

**Comment by Syencil** [comment]
只需要一个onnx就可以了 其他的都是网络自己生成的 默认是FP32 具体可以设置 
只有int8才需要校准表

**Comment by wumei1234** [comment]
> @Syencil
> 在执行./bin/fcos时遇到一个问题：
> [08/07/2020-10:53:38] [E] Serializing Engine Failed
> [08/07/2020-10:53:38] [E] Init Session Failed!
> 
> 操作步骤：
> 1、在tensorRT根目录下mkidr build -> cd build -> cmake .. -> make
> 2、./bin/fcos
> 
> 我发现在执行make以后，并没有产生fcosInt8.calibration文件和fcos.serialized文件，请问是什么原因呢？望解答
> 
> 这是我的CMakeList.txt里的部分路径：
> set(tensorrt_dir /home/_**/programs/tensorRT/3rdParty/tensor-rt) set(project_dir /home/**_/programs/tensorRT)（这个是你的工程的目录）
> include_directories(${tensorrt_dir}/include)
> include_directories(${project_dir}/include)
> link_directories(${tensorrt_dir}/lib)
> link_directories(${project_dir}/source)
> link_directories(${project_dir}/lib)（这个有点奇怪，你的工程的根目录下没有lib文件夹。。。）
> 
> 这是fcos_main里的部分路径：
> trtParams.CalibrationTablePath = "/home/_**/programs/tensorRT/data/fcosInt8.calibration"; trtParams.CalibrationImageDir = ""; trtParams.OnnxPath = "/home/**_/programs/tensorRT/onnx/fcos.onnx";
> trtParams.SerializedPath = "/home/***/programs/tensorRT/data/onnx/fcos.serialized";

你好，我也遇到了和你一样的问题，[E] Serializing Engine Failed[E] Init Session Failed!请问你是怎么解决的呢

**Comment by wumei1234** [comment]
你好，我也遇到了和你一样的问题，请问你解决了吗
[06/04/2021-21:39:00] [E] Serializing Engine Failed
[06/04/2021-21:39:00] [E] Init Session Failed!
[06/04/2021-21:39:00] [I] Pre Process time is 5.04432ms
[06/04/2021-21:39:00] [I] Infer time is 80.1974ms
[06/04/2021-21:39:00] [E] [TRT] INVALID_ARGUMENT: Cannot find binding of given name: 692
Segmentation fault (core dumped)
