### ISSUE TITLE
trtParams.CalibrationTablePath

### ISSUE THREAD

**Issue by zzcqinag** [Syencil/tensorRT#17]
你好! psenetv2 里面 trtParams.CalibrationTablePath和trtParams.SerializedPath这两个参数是怎么定的

**Comment by Syencil** [comment]
> 你好! psenetv2 里面 trtParams.CalibrationTablePath和trtParams.SerializedPath这两个参数是怎么定的

这个是你设置生成的int8表的位置和序列化文件保存位置。如果文件不存在会自动生成，否则使用这个路径文件
