### ISSUE TITLE
这个项目YOLOV5只能用x一个版本吗？

### ISSUE THREAD

**Issue by Ming-Y-ANG** [Syencil/tensorRT#19]
如题

**Comment by Syencil** [comment]
yolo5s，l，x都可以用。如果还需要更轻量，推荐使用 [https://github.com/Syencil/mobile-yolov5-pruning-distillation](https://github.com/Syencil/mobile-yolov5-pruning-distillation)  和yolo5s性能接近，但是只需要一半算力。

**Comment by Ming-Y-ANG** [comment]
我用用yolov5的话，只需用将在原工程下面导出onnx模型 放到这个项目里面就行了吗？然后执行下面的操作
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make + project_lib
make + project_name
./bin/project_name

make + project_lib  这个lib 值得啥
make + project_name  这个是yolov5 maincpp那个文件吗？

**Comment by Syencil** [comment]
Readme里面有需要注意的地方 你可以参考
