### ISSUE TITLE
hand keypoints detection

### ISSUE THREAD

**Issue by SaddamBInSyed** [Syencil/tensorRT#2]
@Syencil 

Is this repo has implementation for hand pose keypoints detection?

please advise

**Comment by Syencil** [comment]
> @Syencil
> 
> Is this repo has implementation for hand pose keypoints detection?
> 
> please advise

I think you can train your own data by my python repo.
please refer to [https://github.com/Syencil/Keypoints](https://github.com/Syencil/Keypoints)<br>
