### ISSUE TITLE
RetinaFace issue on Jetson Nano with TensorRT 7.1.3 & Cuda 10.2

### ISSUE THREAD

**Issue by omair18** [Syencil/tensorRT#23]
Hey @Syencil . 
First of all thank you for the awesome code samples. 

RetinaFace sample works well on TensorRT 7.1.3 with Cuda 11 but fails with no detection on Jetson Nano (TRT 7.1.3 & Cuda 10.2). 

Can you help me in this regard?

**Comment by Syencil** [comment]
I have no idea. you could try yourself.
