### ISSUE TITLE
请教关于pytorch-yolov3-onnx-tensorRT加速问题

### ISSUE THREAD

**Issue by tangsipeng** [Syencil/tensorRT#24]
大佬，我自己尝试将U版的yolov3转onnx转tensorRT，但是测到的速度在pytorch原版上是推理20ms一张图而在tensorRT推理也是差不多这个速度。请问要如何加速呀？转int8吗？

**Comment by Syencil** [comment]
可以先参考另一个issue的内容 https://github.com/Syencil/tensorRT/issues/18
