### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by dengly** [Syencil/tensorRT#25]
参考以下编译，报错。其中执行`make + project_lib`或`make + project_name`会报`make: *** 没有规则可制作目标“+”。 停止。`错误。
```
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make + project_lib
make + project_name
./bin/project_name
```

如果直接`make`报以下错误，请问如何解决或者对依赖库有版本要求
```
[ 28%] Linking CXX executable bin/stream
/usr/bin/ld: 找不到 -lnvinfer
/usr/bin/ld: 找不到 -lnvonnxparser
/usr/bin/ld: 找不到 -lnvinfer
/usr/bin/ld: 找不到 -lnvonnxparser
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/stream.dir/build.make:129：bin/stream] 错误 1
make[1]: *** [CMakeFiles/Makefile2:184：CMakeFiles/stream.dir/all] 错误 2
make: *** [Makefile:84：all] 错误 2
```

**Comment by yulinhuyang** [comment]
同问啊，/usr/bin/ld: 找不到 -lnvinfer，这个设备有，但是make找不到。。

**Comment by yulinhuyang** [comment]
已解决，还是安装问题，可以 

sudo ln -s /home/hvt/Downloads/TensorRT-5.1.5.0/lib/libnvinfer.so /usr/lib/x86_64-linux-gnu/
sudo ln -s /home/hvt/Downloads/TensorRT-5.1.5.0/lib/libnvinfer_plugin.so /usr/lib/x86_64-linux-gnu/
sudo ln -s /home/hvt/Downloads/TensorRT-5.1.5.0/lib/libnvparsers.so /usr/lib/x86_64-linux-gnu/
sudo ln -s /home/hvt/Downloads/TensorRT-5.1.5.0/lib/libnvonnxparser.so /usr/lib/x86_64-linux-gnu/
sudo ln -s /home/hvt/Downloads/TensorRT-5.1.5.0/lib/libnvonnxparser_runtime.so /usr/lib/x86_64-linux-gnu/


或者通过dkpg安装
