### ISSUE TITLE
yolov5s int8量化不出框？

### ISSUE THREAD

**Issue by Wulingtian** [Syencil/tensorRT#28]
您好，fp32测试是正常出框的，int8量化后不出框是怎么回事？

**Comment by Syencil** [comment]
量化表

**Comment by Wulingtian** [comment]
> 量化表

[yolo5Int8.txt](https://github.com/Syencil/tensorRT/files/5825809/yolo5Int8.txt)

**Comment by Wulingtian** [comment]
> > 量化表
> 
> [yolo5Int8.txt](https://github.com/Syencil/tensorRT/files/5825809/yolo5Int8.txt)
![量化解析](https://user-images.githubusercontent.com/20986422/104836923-3a629f00-58ec-11eb-8b84-ed8c0de140c7.png)

**Comment by Syencil** [comment]
我是说这个和你量化的有关系 多用一些具有代表性的训练图片 多一点没关系 有条件就用整个训练集都行 然后检查流程有没有问题

**Comment by Wulingtian** [comment]
> 我是说这个和你量化的有关系 多用一些具有代表性的训练图片 多一点没关系 有条件就用整个训练集都行 然后检查流程有没有问题

我把所有的训练数据加上也不行
