### ISSUE TITLE
are you available?

### ISSUE THREAD

**Issue by seekingdeep** [Syencil/tensorRT#37]
@Syencil Hi there,
i have a task dealing with text detection.
are you available for freelancing?
if so contact me by my email so i can share with you more information.
muharraq@outlook.com

**Comment by Syencil** [comment]
pls give me more details first
luozw1994@outlook.com

**Comment by Syencil** [comment]
> @Syencil Hi there,
> i have a task dealing with text detection.
> are you available for freelancing?
> if so contact me by my email so i can share with you more information.
> [muharraq@outlook.com](mailto:muharraq@outlook.com)

pls give me more details first
luozw1994@outlook.com

**Comment by seekingdeep** [comment]
have a look at the email sent.
