### ISSUE TITLE
编译错误：/usr/bin/ld: cannot find -lfcostrt

### ISSUE THREAD

**Issue by watersounds** [Syencil/tensorRT#38]
jetson Xavier NX，jetpack 4.5，  cuda10.2，tensor rt 7.1.3 

cmake之后直接make，报错：

>[ 31%] Linking CXX executable bin/fcos
/usr/bin/ld: cannot find -lfcostrt
/usr/bin/ld: cannot find -llibnvinfer.so.7.1.3
/usr/bin/ld: cannot find -llibnvonnxparser.so.7.1.3
collect2: error: ld returned 1 exit status
CMakeFiles/fcos.dir/build.make:113: recipe for target 'bin/fcos' failed
make[2]: *** [bin/fcos] Error 1
CMakeFiles/Makefile2:215: recipe for target 'CMakeFiles/fcos.dir/all' failed
make[1]: *** [CMakeFiles/fcos.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

我将CMakeLists.txt中的第56行：
`set(TRT_LIB libnvinfer.so.7.0.0 libnvonnxparser.so.7.0.0 cuda.so)`
 改为：
`set(TRT_LIB /usr/lib/aarch64-linux-gnu/libnvinfer.so.7.1.3 /usr/lib/aarch64-linux-gnu/libnvonnxparser.so.7.1.3 cuda.so)`
说明：我的libnvinfer.so文件在/usr/lib/aarch64-linux-gnu/位置，并且版本是7.1.3，并没有找到7.0.0，所以修改了版本和位置。

然后再make，报错：
>[ 31%] Linking CXX executable bin/fcos
/usr/bin/ld: cannot find -lfcostrt
collect2: error: ld returned 1 exit status
CMakeFiles/fcos.dir/build.make:117: recipe for target 'bin/fcos' failed
make[2]: *** [bin/fcos] Error 1
CMakeFiles/Makefile2:215: recipe for target 'CMakeFiles/fcos.dir/all' failed
make[1]: *** [CMakeFiles/fcos.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

比之前少了两行，但还是没有生成libfcostrt.so这个文件。

**Comment by Syencil** [comment]
看readme

**Comment by watersounds** [comment]
ok,明白了，先`make fcostrt`，再 `make fcos`，就可以了
是可以只编译某一个网络的文件吧
