### ISSUE TITLE
再实际中trt也不存在理想上的动态输入?trt不是支持动态输入阿，像psenet的话肯定需要动态输入阿

### ISSUE THREAD

**Issue by cqray1990** [Syencil/tensorRT#40]

**Comment by Syencil** [comment]
在TRT-7.0及以前 虽然可以动态输入 但是仔细看他内部实现以及官方文档 只是根据你每次不同的输入大小构建了不同的pipeline 简单理解起就是每种不同尺寸都创建好了pipeline之后 依据你不同的输入尺寸去匹配不同的pipeline进行调用 这个和pytorch，tf的动态尺寸输入是完全不一样的
