### ISSUE TITLE
CalibrationTablePath and SerializedPath

### ISSUE THREAD

**Issue by chaos1992** [Syencil/tensorRT#6]
hi, could you please tell me how can I get CalibrationTablePath file and SerializedPath file? 
Thanks, look forward for your reply

**Comment by Syencil** [comment]
It will be generated by program

**Comment by chaos1992** [comment]
@Syencil hi, when I run cmake, I got the error, can you give me some advice?
----------------------------------------------------------------------------
_CMake Error at CMakeLists.txt:31 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed._
----------------------------------------------------------------------------
PS: I have changed opencv path in CMakelist, just like change 'set(OpenCV_LIBRARY_DIRS /usr/local/lib)'  to 'set(OpenCV_LIBRARY_DIRS /PATH/opencv/lib)'
Thanks, look forward your reply!

**Comment by Syencil** [comment]
be sure opencv installed correctly
