### ISSUE TITLE
TRT plugin的相关疑问？

### ISSUE THREAD

**Issue by BaofengZan** [Syencil/tensorRT#7]
作者你好，对于TRT不支持的层是如何处理的呢？ 比如Unsample层？ 期待回复

**Comment by Syencil** [comment]
trt7是支持upsample的 uff或者caffe的话直接在trt用IPlugin写插件 ONNX的话得在onnx-trt这个git里面写了重新编译lib（比较麻烦） 一般来说能在python代码里面进行修改的就直接改了方便点。

**Comment by BaofengZan** [comment]
谢谢回复，我了解了

**Comment by xjsxujingsong** [comment]
Yolo3的tensorflow代码被删除了？链接打不开了。想看看怎么转upsample层的

**Comment by Syencil** [comment]
> Yolo3的tensorflow代码被删除了？链接打不开了。想看看怎么转upsample层的

upsample现在trt已经支持了
