### ISSUE TITLE
冻结图

### ISSUE THREAD

**Issue by JeQer** [Syencil/tensorRT#8]
在tf2中如何将yolov3转换为冻结图，并生成对应的.pb文件？

**Comment by Syencil** [comment]
https://github.com/onnx/tensorflow-onnx

**Comment by JeQer** [comment]
https://github.com/Syencil/tensorflow-yolov3没有了，能否重新上传您的项目，我使用原版代码无法完成.pb到.onnx的转换

**Comment by Syencil** [comment]
可以参考yolov3的注意事项 走标准的tf1.x freeze流程即可得到

**Comment by JeQer** [comment]
为什么要在yolov3.py中添加一个decode_full_shape方法，这个方法不是和原版源码里的decode一模一样的逻辑吗

**Comment by Syencil** [comment]
方便操作
