### ISSUE TITLE
how to build in win10?

### ISSUE THREAD

**Issue by chunniunai220ml** [Syencil/tensorRT#9]
Hi,thank for your shareing. But i have some problems when I cmake in win10.
 here is my cmakelist(only build retinaface):

cmake_minimum_required(VERSION 3.5)
project(tensorRT)
set_property(GLOBAL PROPERTY USE_FOLDERS on)

# output
set(EXECUTABLE_OUTPUT_PATH "${PROJECT_BINARY_DIR}/bin")
message(STATUS "Project_binary_dir : ${PROJECT_BINARY_DIR}")
# c++ 11
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")

# tensorRT
set(tensorrt_dir D:/c/TensorRT-7.0.0.11.Windows10.x86_64.cuda-10.0.cudnn7.6/TensorRT-7.0.0.11)
set(project_dir my/path/to/tensorRT-7)
include_directories(${tensorrt_dir}/include)
include_directories(${project_dir}/include)
link_directories(${tensorrt_dir}/lib)
link_directories(${project_dir}/source)
link_directories(${project_dir}/lib)

# Loggers
aux_source_directory(${common_dir}/source common_src)
set(COMMON_SRC ${common_src} CACHE INTERNAL "common_source" )
set(LOGGER_SRC ${common_dir}/source/logger.cpp CACHE INTERNAL "logger" )

message(STATUS "TensorRT Header => ${tensorrt_dir}/include")
message(STATUS "TensorRT Lib => ${tensorrt_dir}/lib")

# find opencv
find_package(OpenCV REQUIRED)
include_directories(${OpenCV_INCLUDE_DIRS})
if(NOT OpenCV_LIBRARY_DIRS)
    set(OpenCV_LIBRARY_DIRS D:/software/opencv/build/x64/vc14/lib)
    message(WARING " Can not find opencv lib. It will use the default path => ${OpenCV_LIBRARY_DIRS}")
endif()
link_directories(${OpenCV_LIBRARY_DIRS})
message(STATUS "OpenCV_INCLUDE_DIRS => ${OpenCV_INCLUDE_DIRS}")
message(STATUS "OpenCV_LIBRARY_DIRS => ${OpenCV_LIBRARY_DIRS}")

if(NOT OpenCV_FOUND)
    message(ERROR "OpenCV not found!")
endif(NOT OpenCV_FOUND)

# find cuda
find_package(CUDA)
find_package(CUDA REQUIRED)

#include_directories(${CUDA_INCLUDE_DIRS})
include_directories(C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/include)
if(NOT CUDA_LIBRARY_DIRS)
    set(CUDA_LIBRARY_DIRS C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64)
    message(WARING " Can not find CUDA lib. It will use the default path => ${CUDA_LIBRARY_DIRS}")
endif()
link_directories(${CUDA_LIBRARY_DIRS})
message(STATUS "CUDA_INCLUDE_DIRS : ${CUDA_INCLUDE_DIRS}")
message(STATUS "CUDA_LIBRARY_DIRS : ${CUDA_LIBRARY_DIRS}")

###############################################
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${project_dir}/lib)
set(TRT source/tensorrt.cpp source/logger.cpp source/utils.cpp source/utils.cu)
set(INT8 source/Int8Calibrator.cu source/Int8Calibrator.cpp)

set(RETINAFACE ${TRT} ${INT8} source/retinaface.cpp)

set(CV_LIB libopencv_core.so libopencv_imgproc.so libopencv_imgcodecs.so)
set(TRT_LIB libnvinfer.so libnvonnxparser.so cudart.so)

cuda_add_executable(retinaface retinaface_main.cpp)
target_link_libraries(retinaface retinafacetrt.so ${TRT_LIB} ${CV_LIB})

#########################3#####################
cuda_add_library(retinafacetrt SHARED ${RETINAFACE})

the "set(project_dir /work/tensorRT-7) ",what is  means of the file :tensorRT-7?  I can  not generate this and find in gits file.

I can cmake/build successfully with compiler VNC14 and generate tensorRT.sln. BUT, it can not open retinaface.h when I debug the .sln, fatal error: no such file in retinaface.vcxproj.
and do not generate retinafaceInt8.calibration and retinafaceInt8.calibration.
 so what should I do for compiling in win10?

**Comment by Syencil** [comment]
it's work dir

**Comment by chunniunai220ml** [comment]
> it's work dir
I GOT IT,but  are you test the project in win10?   and if you test, can you share the fps with me ? 
I can cmake/build successfully with compiler VNC14 and generate tensorRT.sln. BUT, it can not open retinaface.h when I debug the .sln, fatal error: no such file in retinaface.vcxproj.
and do not generate retinafaceInt8.calibration and retinafaceInt8.calibration.
i have not solve this problem.

**Comment by Syencil** [comment]
all the works have been done in linux and Tesla-P GPU. Inference FPS can achive 425FPS. Total inference time included pre/post time can be compressed into 12ms. there are still something can be optimized and just try yourself
